theme: minima
title: From Code to Capital
author: Jatin Momaya
description: A blog capturing the learnings, insights, and experiences from my career journey, alongside my curious explorations into various topics like product management, technology, and venture capitalism.
