theme: minima
title: From Code to Capital
author: Jatin Momaya
description: he/him 23 y/o Los Angeles, CA 

email: "momayajatin@gmail.com"
twitter_username: "@jatin_momaya"
github_username: "jatinmomaya"
linkedin_username: "jatin-momaya"
